# Generated by Django 5.0.2 on 2024-02-21 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonuser',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_users', to='training.lesson'),
        ),
    ]
